DELETE from script_texts WHERE entry BETWEEN -1789927 AND -1789900;
INSERT into script_texts (entry,content_default,type,comment) VALUES
(-1789900,'Stand back, $N, the beast might lash out and harm you.',0,'HALLARD_SAY_1'),
(-1789901,'GODFREY! Hear me, fiend! Hear me, for I am the Light, here to deliver you from evil!',0,'HALLARD_SAY_2'),
(-1789902,'Mayor Godfrey growls',2,'GODFREY_EMOTE_1'),
(-1789903,'Good. I have your attention, then, Godfrey?',0,'HALLARD_SAY_3'),
(-1789904,'We can do this in one of two ways, Godfrey. First, I will simply ask you to tell me what the unholy markings etched upon the pages of this tome mean. What say you?',0,'HALLARD_SAY_4'),
(-1789905,'Mayor Godfrey hisses!',2,'GODFREY_EMOTE_2'),
(-1789906,'Tell you nothing, preacher.',0,'GODFREY_SAY_1'),
(-1789907 ,'What can you do to me that KelThuzad has not? That the Lich King will not?',0,'GODFREY_SAY_2'),
(-1789908,'The book is your salvation, yes... but nothing will you know! NOTHING I SAY! NOTHING! ',0,'GODFREY_SAY_3'),
(-1789909,'Then it is option two.',0,'HALLARD_SAY_5'),
(-1789910,'Let the sermon begin.',0,'HALLARD_SAY_7'),
(-1789911,'The power of the Lich King pales in comparison to the glory of the Light!',0,'HALLARD_SAY_8'),
(-1789912,'BURN IN HOLY FIRE!',0,'HALLARD_SAY_9'),
(-1789913,'Do not fight me, fiend! The time of your atonement is now!',0,'HALLARD_SAY_10'),
(-1789914,'IT BURNSSSSS! ',0,'GODFREY_SAY_4'),
(-1789915,'The pain is unbearable! ',0,'GODFREY_SAY_5'),
(-1789916,'I thought you would see the Light, Godfrey... Now speak quickly, fiend. What does it say?',0,'HALLARD_SAY_11'),
(-1789917,'It tells of the coming apocalypse. How this world will burn and be reborn from death. ',0,'GODFREY_SAY_6'),
(-1789918,'RUBBISH! Godfrey do you take me for a fool? Do not spew your Scourge propoganda at a man of the Light, heathen! Speak now or I will have the peasants craft a holy water bath and dip you into it like a dog with fleas!',0,'HALLARD_SAY_12'),
(-1789919,'NOOOO! I tell you! I tell you everything! ',0,'GODFREY_SAY_7'),
(-1789920,'Humans... Beneath the earth of Wintergarde Village you built a mausoleum! Why do you think Naxxramas attacked that spot? Thelzan hides deep in your own crypt and sends a thousand-thousand corpses at you! Perish you will... ',0,'GODFREY_SAY_8'),
(-1789921,'What? There is a mausoleum beneath the old village? What fools we are to not have noticed! We will find and strike down your master now, Godfrey. We will end this nightmare.',0,'HALLARD_SAY_13'),
(-1789922,'How? Humans truly are stupid, yes? Thelzan the Duskbringer! Thelzan the Lich! He who is born of human flesh and bone, sacrificed all for power, protected by the Lich King!',0,'GODFREY_SAY_9'),
(-1789923,'You cannot stop Thezan! He bears the dark gift, bestowed upon him by the Lich King himself!',0,'GODFREY_SAY_10'),
(-1789924,'You let us worry about how we kill the monster, Godfrey.',0,'HALLARD_SAY_14'),
(-1789925,'Return to Halford with the information that the good mayor was kind enough to submit, $N. I will finish here and squeeze whatever else this wretch might know about Thel\'zan. Now, I will show Godfrey the rarely seen "option three."',0,'HALLARD_SAY_15'),
(-1789926,'Let\'s you and I have a chat about some things, Godfrey.',0,'HALLARD_SAY_16'),
(-1789927,'I say a prayer for you now, lost soul. May the Light take you gracefully.',0,'HALLARD_SAY_6');
